<?php

namespace App\Jobs\Editor;

use App\Jobs\Concerns\RunsInProject;
use App\Services\Capture\SiteFootage;
use App\Services\Clips\Contracts\RemotionRenderer;
use App\Services\Clips\EffectGenerator;
use App\Services\Clips\EffectLibrary;
use App\Services\Editor\CutPlan;
use App\Services\Editor\EditorStore;
use App\Services\Editor\SfxOverlayEngine;
use App\Services\Editor\SfxPlanner;
use App\Services\Shorts\LocalVideoEngine;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\Middleware\WithoutOverlapping;
use Illuminate\Support\Str;

/**
 * Step 2: propose effects for the finished cut, build each one, and lay them
 * over the screen feed.
 *
 * Each effect is generated by the SAME EffectGenerator the SFX/VFX studios use —
 * so it obeys the design-system guard — and rendered with alpha through the
 * isolated candidate composition, then composited at its moment.
 */
class GenerateEditSfxJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, RunsInProject;

    public int $timeout = 7200;

    public function __construct(public string $editId)
    {
        $this->captureProject();
    }

    /**
     * Shares the effect-generation lock: GenerateEffectJob, GenerateVfxJob and
     * this one all write the single remotion/src/effects/_candidate.tsx slot, so
     * running two at once would render one job's component into the other's file.
     */
    public function middleware(): array
    {
        return [(new WithoutOverlapping('generate-effect'))->releaseAfter(60)->expireAfter(7200)];
    }

    public function handle(
        EditorStore $store,
        CutPlan $plan,
        SfxPlanner $planner,
        EffectGenerator $generator,
        EffectLibrary $library,
        RemotionRenderer $renderer,
        SfxOverlayEngine $overlay,
        LocalVideoEngine $engine,
    ): void {
        $this->activateProject();

        $edit = $store->find($this->editId);
        if (! $edit) {
            return;
        }

        $screen = (string) ($edit->get('outputs')['screen'] ?? '');
        if ($screen === '' || ! is_file($screen)) {
            $edit->update(['sfx_error' => 'There is no edited screen feed to place effects on.']);

            return;
        }

        $edit->update(['sfx_status' => 'working', 'sfx_error' => null]);
        $temporarios = [];

        try {
            // Effects sit on the EDITED timeline, so plan from the cut transcript.
            $ranges = $plan->keepRanges($edit->removals(), (float) $edit->get('duration', 0));
            $momentos = $planner->plan($plan->editedSegments($edit->transcript(), $ranges));

            if ($momentos === []) {
                $edit->update(['sfx_status' => 'none', 'sfx' => []]);

                return;
            }

            [$largura, $altura] = $this->dimensoes($engine, $screen);

            $colocacoes = [];
            $resumo = [];

            foreach ($momentos as $i => $momento) {
                $canvas = ['width' => $largura, 'height' => $altura, 'transparent' => true];

                $site = app(SiteFootage::class)
                    ->forPrompt($momento['brief'], $largura, $altura, (float) $momento['duration']);

                $data = $generator->generate($momento['brief'], canvas: $canvas, siteCapture: $site['path']);
                $library->writeCandidate($data['tsx']);

                // ProRes 4444 with alpha must be a .mov.
                $ficheiro = tempnam(sys_get_temp_dir(), 'edit_sfx_').'.mov';
                $temporarios[] = $ficheiro;

                $renderer->render(
                    $library->candidateSampleProps($data['sample_text'], $data['sample_params'], $canvas + [
                        'duration' => (float) $momento['duration'],
                    ]),
                    $ficheiro,
                    'src/sample.ts',
                    'SampleEffect'
                );

                $colocacoes[] = ['path' => $ficheiro, 'at' => $momento['at'], 'duration' => $momento['duration']];
                $resumo[] = [
                    'at' => $momento['at'],
                    'duration' => $momento['duration'],
                    'brief' => $momento['brief'],
                    'over' => $momento['text'],
                    'name' => $data['display_name'] ?? 'Effect '.($i + 1),
                    'site_url' => $site['url'],
                ];
            }

            $destino = $store->filePath($edit->id(), 'screen-sfx');
            $tmp = $destino.'.part';
            $overlay->apply($screen, $colocacoes, $tmp);
            @rename($tmp, $destino);

            $edit->update([
                'sfx_status' => 'done',
                'sfx' => $resumo,
                'outputs' => array_merge((array) $edit->get('outputs', []), ['screen_sfx' => $destino]),
            ]);
        } catch (\Throwable $e) {
            $edit->update([
                'sfx_status' => 'failed',
                'sfx_error' => Str::limit($e->getMessage(), 500),
            ]);
        } finally {
            $library->resetCandidate();
            foreach ($temporarios as $f) {
                @unlink($f);
            }
        }
    }

    /** The screen feed's own size, so the overlay lines up pixel for pixel. */
    private function dimensoes(LocalVideoEngine $engine, string $video): array
    {
        $meta = $engine->probe($video);
        $largura = (int) ($meta['width'] ?? 0);
        $altura = (int) ($meta['height'] ?? 0);

        return [$largura > 0 ? $largura : 1920, $altura > 0 ? $altura : 1080];
    }
}
