import type React from "react";
import type { PrimitiveProps } from "../primitives";

// AUTO-GENERATED by App\Services\Clips\BackgroundLibrary::syncFilesystem().
// Do NOT edit by hand — it is rebuilt from the active project's background records.
export const CUSTOM_BACKGROUNDS: Record<string, React.FC<PrimitiveProps>> = {};
