<?php

namespace App\Services\Aggregation;

use App\Services\Settings\SettingsRepository;
use App\Services\Vault\VaultContract;
use Illuminate\Support\Str;

/**
 * Orchestrates multi-platform aggregation: collects items from the configured channels,
 * archives them in the vault organized BY DAY and generates, per day, a topics note
 * ("what has already been covered and is live").
 */
class NewsAggregator
{
    /**
     * Platforms that yt-dlp collects reliably. Instagram/TikTok/LinkedIn
     * are «marked as broken» in yt-dlp (they need Apify) — they are skipped with
     * a warning until that integration exists.
     */
    private const SUPORTADAS = ['youtube'];

    public function __construct(
        private readonly VaultContract $vault,
        private readonly SettingsRepository $definicoes,
        private readonly YtDlpRunnerContract $runner,
        private readonly TranscriptParser $parser,
        private readonly TopicsBuilder $topicos,
        private readonly LlmClient $llm,
    ) {}

    /**
     * Runs the aggregation and writes to the vault.
     *
     * @param  array<int,string>|null  $plataformas  Limits to these platforms (null = all configured).
     * @return array{gerado_em:string,total:int,por_plataforma:array<string,int>,dias:array<int,string>,avisos:array<int,string>}
     */
    public function aggregate(?array $plataformas = null, ?int $limite = null): array
    {
        $limite ??= (int) config('contentmachine.aggregation.limite_por_canal', 5);
        $canaisConfig = (array) $this->definicoes->get('canais', []);
        $plataformas ??= array_keys($canaisConfig);

        $todos = [];
        $porPlataforma = [];
        $avisos = [];

        foreach ($plataformas as $plataforma) {
            $canais = array_values(array_filter((array) ($canaisConfig[$plataforma] ?? [])));
            if ($canais === []) {
                continue;
            }

            // Skip platforms that yt-dlp cannot collect (avoids calls
            // that fail/hang and blow the request timeout).
            if (! in_array($plataforma, self::SUPORTADAS, true)) {
                $porPlataforma[$plataforma] = 0;
                $avisos[] = $this->avisoIndisponivel($plataforma);

                continue;
            }

            $itens = $this->driver($plataforma)->collect($canais, $limite);
            $porPlataforma[$plataforma] = count($itens);

            if ($itens === []) {
                $avisos[] = $this->avisoIndisponivel($plataforma);
            }

            foreach ($itens as $item) {
                $this->arquivarItem($item);
                $todos[] = $item;
            }
        }

        $dias = $this->arquivarTopicos($todos);

        return [
            'gerado_em' => now()->toIso8601String(),
            'total' => count($todos),
            'por_plataforma' => $porPlataforma,
            'dias' => $dias,
            'avisos' => $avisos,
        ];
    }

    /** Creates the driver suited to the platform. All use yt-dlp at the moment. */
    private function driver(string $plataforma): AggregatorDriver
    {
        return new YtDlpDriver($this->runner, $this->parser, $plataforma);
    }

    private function arquivarItem(AggregatedItem $item): void
    {
        $corpo = $item->descricao !== ''
            ? "## Descrição\n\n{$item->descricao}\n\n## Transcrição\n\n".($item->transcricao ?: '_Sem transcrição disponível._')
            : "## Transcrição\n\n".($item->transcricao ?: '_Sem transcrição disponível._');

        $this->vault->put($item->caminho(), [
            'titulo' => $item->titulo,
            'tipo' => 'item_agregado',
            'plataforma' => $item->plataforma,
            'canal' => $item->canal,
            'data' => $item->dia(),
            'url' => $item->url,
            'thumbnail' => $item->thumbnail,
            'descricao' => Str::of($item->descricao)->squish()->limit(800)->toString(),
            'resumo' => $this->resumoDoItem($item),
            'tags' => $item->tags,
            'fontes' => $item->fontes,
        ], $corpo);
    }

    /**
     * Content summary (1-2 sentences) of what the video COVERS, generated by LLM
     * from the transcript — not the author's promotional description. Without LLM or
     * without a transcript returns empty (the interface falls back to the start of the transcript).
     */
    private function resumoDoItem(AggregatedItem $item): string
    {
        $transcricao = trim($item->transcricao);
        if ($transcricao === '' || ! config('contentmachine.aggregation.gerar_resumos', true) || ! $this->llm->disponivel()) {
            return '';
        }

        $prompt = 'In 1 to 2 short sentences and in EUROPEAN PORTUGUESE, summarize WHAT THIS VIDEO COVERS '
            .'(the content addressed, not promotions, sponsorships or links). Respond only with the summary, no quotes.'
            ."\n\nTitle: {$item->titulo}\nTranscript (excerpt): ".Str::limit($transcricao, 3000, '');

        $resumo = $this->llm->texto($prompt);

        return $resumo !== null ? Str::of($resumo)->squish()->limit(400)->toString() : '';
    }

    /**
     * Groups by day and writes/updates each day's topics note.
     *
     * @param  array<int,AggregatedItem>  $itens
     * @return array<int,string> affected days (YYYY-MM-DD)
     */
    private function arquivarTopicos(array $itens): array
    {
        $porDia = [];
        foreach ($itens as $item) {
            $porDia[$item->dia()][] = $item;
        }

        krsort($porDia);

        foreach ($porDia as $dia => $itensDoDia) {
            $resultado = $this->topicos->build($itensDoDia);
            $this->vault->put(
                "noticias/{$dia}/topicos.md",
                [
                    'titulo' => "Tópicos — {$dia}",
                    'tipo' => 'topicos',
                    'data' => $dia,
                    'metodo' => $resultado['metodo'],
                    'total' => count($itensDoDia),
                ],
                $this->corpoTopicos($dia, $resultado, count($itensDoDia)),
            );
        }

        return array_keys($porDia);
    }

    /** @param array<string,mixed> $resultado */
    private function corpoTopicos(string $dia, array $resultado, int $total): string
    {
        $linhas = [
            "# Tópicos cobertos — {$dia}",
            '',
            "> {$total} item(s) agregado(s) · método: {$resultado['metodo']} · {$resultado['gerado_em']}",
            '',
        ];

        foreach ($resultado['topicos'] as $topico) {
            $linhas[] = "## {$topico['topico']}";
            $linhas[] = '';

            foreach ($topico['itens'] as $it) {
                $plataforma = $it['plataforma'] ?? '';
                $url = $it['url'] ?? '';
                $titulo = $it['titulo'] ?? '';
                $linhas[] = $url !== ''
                    ? "- **[{$plataforma}]** [{$titulo}]({$url})"
                    : "- **[{$plataforma}]** {$titulo}";
            }

            if (! empty($topico['fontes'])) {
                $linhas[] = '';
                $linhas[] = '  Fontes: '.implode(' · ', array_map(fn ($f) => "<{$f}>", $topico['fontes']));
            }

            $linhas[] = '';
        }

        return implode("\n", $linhas);
    }

    private function avisoIndisponivel(string $plataforma): string
    {
        return match ($plataforma) {
            'instagram', 'tiktok', 'linkedin' => ucfirst($plataforma).': skipped — for now only YouTube is collected (the other platforms need Apify).',
            default => ucfirst($plataforma).': no items collected (channel unreachable or no recent posts).',
        };
    }
}
