import type React from "react";
import type { PrimitiveProps } from "../primitives";
import Effect_image_drop_bounce from "./image-drop-bounce";
import Effect_image_slide_caption from "./image-slide-caption";

// AUTO-GENERATED by App\Services\Clips\EffectLibrary::syncFilesystem().
// Do NOT edit by hand — it is rebuilt from the active `clip_effects` rows.
export const CUSTOM_PRIMITIVES: Record<string, React.FC<PrimitiveProps>> = {
  "image-drop-bounce": Effect_image_drop_bounce,
  "image-slide-caption": Effect_image_slide_caption,
};
