import type React from "react";
import type { PrimitiveProps } from "../primitives";

// AUTO-GENERATED by App\Services\Clips\EffectLibrary::syncFilesystem().
// Do NOT edit by hand — it is rebuilt from the active project's SFX records.
export const CUSTOM_PRIMITIVES: Record<string, React.FC<PrimitiveProps>> = {};
