import type React from "react";
import type { PrimitiveProps } from "../primitives";
import Effect_diagram from "./diagram";
import Effect_timeline from "./timeline";
import Effect_particle_image_assemble from "./particle-image-assemble";
import Effect_image_diagram from "./image-diagram";
import Effect_circular_diagram from "./circular-diagram";
import Effect_non_linear_diagram from "./non-linear-diagram";
import Effect_image_slide_caption from "./image-slide-caption";
import Effect_image_drop_bounce from "./image-drop-bounce";

// AUTO-GENERATED by App\Services\Clips\EffectLibrary::syncFilesystem().
// Do NOT edit by hand — it is rebuilt from the active project's SFX records.
export const CUSTOM_PRIMITIVES: Record<string, React.FC<PrimitiveProps>> = {
  "diagram": Effect_diagram,
  "timeline": Effect_timeline,
  "particle-image-assemble": Effect_particle_image_assemble,
  "image-diagram": Effect_image_diagram,
  "circular-diagram": Effect_circular_diagram,
  "non-linear-diagram": Effect_non_linear_diagram,
  "image-slide-caption": Effect_image_slide_caption,
  "image-drop-bounce": Effect_image_drop_bounce,
};
