<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * A custom SFX: a Remotion primitive component generated from a text
 * description. The DB row is the source of truth; the filesystem
 * (remotion/src/effects/{slug}.tsx + index.ts) is rebuilt from the active rows
 * by EffectLibrary::syncFilesystem().
 */
class ClipEffect extends Model
{
    public const STATUS_PENDING = 'pending';

    public const STATUS_ACTIVE = 'active';

    public const STATUS_FAILED = 'failed';

    // Active effect being regenerated by an edit — kept out of active() until the
    // new version passes, so a failed edit leaves the live version untouched.
    public const STATUS_UPDATING = 'updating';

    protected $guarded = [];

    protected $attributes = [
        'status' => self::STATUS_PENDING,
        'enabled' => true,
    ];

    protected $casts = [
        'sample_params' => 'array',
        'enabled' => 'boolean',
    ];

    public function isActive(): bool
    {
        return $this->status === self::STATUS_ACTIVE;
    }
}
